[framework]
name = "Simple"
hbs = """
{{chat.input}}
"""

[page]
name = "Page"
hbs = """
<webpage_info>
Below are some potentially helpful/relevant pieces of information for figuring out to respond

{{#if page.title}}<title>{{page.title}}</title>{{/if}}
{{#if page.url}}<url>{{page.url}}</url>{{/if}}
{{#if page.content}}<content>{{page.content}}</content>{{/if}}
{{#if page.selection}}<selection>{{page.selection}}</selection>{{/if}}

</webpage_info>

<user_query>
{{chat.input}}
</user_query>
"""

[explain]
name = "Explain"
hbs = """
Explain
{{page.selection}}
{{chat.input}}
"""

[summarize]
name = "Summarize"
hbs = """
{{#if page.content}}
<content>
{{page.content}}
</content>
{{/if}}
Summarize
{{chat.input}}
"""


[translate-to-zh]
name = "Chinese"
hbs = """
请翻译成中文: 
{{page.selection}}
{{chat.input}}
"""

[translate-to-en]
name = "English"
hbs = """
Translate to English:
{{page.selection}}
{{chat.input}}
"""
