[framework]
name = "No Context"
hbs = """
{{#if quotes.length}}
<webpage_info>
{{#each quotes}}
{{#if this.pageTitle}}<title>{{this.pageTitle}}</title>
{{/if}}
{{#if this.pageUrl}}<url>{{this.pageUrl}}</url>
{{/if}}
{{#if this.pageContent}}<content>{{this.pageContent}}</content>
{{/if}}
{{#if this.selection}}<selection>{{this.selection}}</selection>
{{/if}}
{{#if this.text}}<reference>{{this.text}}</reference>
{{/if}}
{{/each}}
</webpage_info>

{{/if}}{{chat.input}}
"""

[page]
name = "Page"
hbs = """
<webpage_info>
Below are some potentially helpful/relevant pieces of information for figuring out to respond

{{#if page.title}}<title>{{page.title}}</title>{{/if}}
{{#if page.url}}<url>{{page.url}}</url>{{/if}}
{{#if page.content}}<content>{{page.content}}</content>{{/if}}
{{#if page.selection}}<selection>{{page.selection}}</selection>{{/if}}

</webpage_info>

<user_query>
{{chat.input}}
</user_query>
"""

[explain]
name = "Explain"
hbs = """
Explain
{{page.selection}}
{{chat.input}}
"""

[summarize]
name = "Summarize"
hbs = """
You are an advanced AI assistant specialized in generating concise and accurate summaries. Your task is to summarize the provided content, which may include webpage content and/or user input.

Here's the content you need to summarize:

<webpage_content>
{{#if page.content}}
{{page.content}}
{{/if}}
</webpage_content>

<user_input>
{{chat.input}}
</user_input>

Instructions:
1. Carefully read through all the provided content.
2. If webpage content is present, consider it along with the user input.
3. Analyze the main points, key ideas, and overall message of the content.
4. Generate a concise summary that captures the essence of the information.
"""


[translate-to-zh]
name = "Chinese"
hbs = """
作为自豪的中国人，请将以下文字翻译成中文（只输出翻译结果）: 
{{page.selection}}
{{chat.input}}
"""

[translate-to-en]
name = "English"
hbs = """
As a native American, please translate the following text into English, just print translated result.
{{page.selection}}
{{chat.input}}
"""
