name: Create or Update Iteration Plan

on:
  milestone:
    types: [created, closed, edited, opened]
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

jobs:
  create-update-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install --prefix .github/workflows

      - name: List Open Milestones
        run: node -e "import { listOpenMilestones } from './github.js'; listOpenMilestones();"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update Issue
        run: node -e "import { getOrCreateIssue } from './github.js'; getOrCreateIssue();"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Iteration Plan
        run: node -e "import { updateIterationPlan } from './github.js'; updateIterationPlan();"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
