name: Create or Update Iteration Plan

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

jobs:
  create-update-issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Log event details
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --prefix .github/workflows

      - name: Check issue title
        id: check_title
        run: echo "::set-output name=skip::$(echo '${{ github.event.issue.title }}' | grep -q 'Iteration Plan for' && echo true || echo false)"

      - name: Run GitHub Script
        if: steps.check_title.outputs.skip == 'false'
        run: node .github/workflows/github.js
        env:
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
