name: Create or Update Iteration Plan

on:
  milestone:
    types: [created, closed, edited, opened]
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

jobs:
  create-update-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install --prefix .github/workflows

      - name: Run GitHub Script
        run: node .github/workflows/github.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
